chore(ci): disable fail-fast on build job
ionic-team/stencil-store pull request #327
Opened 2023-06-30 19:58 UTC by rwaskiewicz

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Tests (`npm test`) were run locally and passed
- [ ] Prettier (`npm run prettier`) was run locally and passed

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

GitHub Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Testing

## Other information

2023-07-03 15:05 UTC, alicewriteswrongs approved these changes

2023-07-05 15:03 UTC, tanner-reits requested changes
Looks like an artifact got tracked with this (assuming that's what prompted [this PR](#326)). Revert that and we're g2g

2023-07-13 13:17 UTC, rwaskiewicz commented
@tanner-reits fixed in 70c9b3a3f174acec76f36a77317e32dd37781bf5

2023-07-13 13:18 UTC, tanner-reits approved these changes

2023-07-13 13:20 UTC, merged