chore(ci): add automated dev releases
ionic-team/stencil-store pull request #450
Opened 2024-01-26 15:10 UTC by rwaskiewicz

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Tests (`npm test`) were run locally and passed
- [x] Prettier (`npm run prettier`) was run locally and passed

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Dev releases don't exactly exist for this project. Prereleases are cut and published to the npm registry.

GitHub Issue Number: N/A

## What is the new behavior?

this commit implements an initial workflow for dev releases for stencil
store. it is capable of:

- generating a build based using the same logic as other ci workflows
- generating a dev build version
- invoking a publish action with the dev version & 'dev' tag

a new publish action is added that is capable of incrementing the
version of the package and publishing changes to npm has been added. the
intent is to reuse this in some capacity for production releases.

this commit also includes additional actions for building the project &
downloading/uploading archives. to date, ci has been rather simplistic
in this repo. however, it's planned to integrate these actions into
existing workflows once this has been added to `main`.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Testing

In ee04f5e2583b50e5f0f46ceae304e74a831b6399, I had a push event trigger enabled such that when I pushed this branch to GitHub, a dev build would get triggered. I considered this to be safe because:
1. It built off the same workflow/steps as the create-stencil cli, which has dev releases
2. I tested this _without_ publishes enabled at first (commented out) - but I've squashed that commit away since then
3. I figured worst case, since I verified the tag and version number, I'd push a bad dev release to npm 
4. https://github.com/ionic-team/stencil-store/actions/runs/7668950038 shows a successful publish to the npm registry
<img width="820" alt="Screenshot 2024-01-26 at 10 10 24 AM" src="https://github.com/ionic-team/stencil-store/assets/1930213/c67b6ab1-3461-482f-aac7-9c057db7a4b7">

## Other information

2024-01-26 16:19 UTC, christian-bromann approved these changes
LGTM 👍 

Question: should we also add a prod release pipeline?

2024-01-26 16:58 UTC, rwaskiewicz commented
> Question: should we also add a prod release pipeline?

Yep, we will - I wanted to get this landed/working first 🙂

2024-02-09 19:29 UTC, alicewriteswrongs requested changes
action run looks good, code all looks straightforward, just had really one question

2024-02-09 19:29 UTC, alicewriteswrongs commented on .github/workflows/actions/download-archive/action.yml
> +name: 'Create Stencil Store Archive Download'
should this be

```suggestion
name: 'Stencil Store Archive Download'
```

2024-02-09 19:29 UTC, alicewriteswrongs commented on .github/workflows/build.yml
(which would obviate the need for uploading and downloading and whatnot)

2024-02-09 19:30 UTC, rwaskiewicz commented on .github/workflows/actions/download-archive/action.yml
> +name: 'Create Stencil Store Archive Download'
Yup! Thanks copy/paste 😆

2024-02-09 19:33 UTC, rwaskiewicz commented on .github/workflows/build.yml
> is the thought that we'd want to re-use this for prod releases or something at some point? j/w/ because if we don't have that aspiration I supposed that all the steps to build and publish could be in one single workflow

Yup - exactly that!

2024-02-09 19:39 UTC, alicewriteswrongs approved these changes

2024-02-09 20:40 UTC, merged